{
   "log":{
      "access":"none",
      "loglevel":"warning"
   },
   "inbounds":[
      {
         "port":443,
         "protocol":"vless",
         "settings":{
            "clients":[
               {
                  "id":"FILL ME"
               }
            ],
            "decryption":"none"
         },
         "streamSettings":{
            "network":"gun",
            "security":"tls",
            "tlsSettings":{
               "alpn":[
                  "h2",
                  "http/1.1"
               ],
               "certificates":[
                  {
                     "certificateFile":"FILL ME",
                     "keyFile":"FILL ME"
                  }
               ]
            },
            "grpcSettings":{
               "serviceName":"RANDOM"
            }
         }
      },
      {
         "listen":"0.0.0.0",
         "port":8080,
         "protocol":"vmess",
         "settings":{
            "clients":[
               {
                  "id":"FILL ME"
               }
            ]
         },
         "streamSettings":{
            "network":"ws",
            "wsSettings":{
               "path":"A RANDOM THING"
            },
            "security":"none"
         }
      }
   ],
   "outbounds":[
      {
         "protocol":"freedom"
      }
   ]
}
